services:
  web:
    build: ./backend_sleepinIn
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_sleepinIn/:/usr/src/backend_sleepinIn/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sleepinInDB
      - POSTGRES_USER=sleepinInDB
      - POSTGRES_PASSWORD=sleepinInDB
    ports:
      - "5432:5432"
volumes:
  postgres_data:
